name: musicplay
description: "A music streaming app with gamification features"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1

  # State Management
  provider: ^6.1.1

  # Audio & Media
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.2
  cached_network_image: ^3.3.1

  # Utilities
  http: ^1.2.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.3
  file_picker: ^6.1.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true