// File generated by FlutterFire CLI.
// Replace these values with your actual Firebase project configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvvaD1lsnY91nnQg_hQrvZbtf8wrVfvQ',
    appId: '1:881231813947:android:59596f1a76c78539e8ab1e',
    messagingSenderId: '881231813947',
    projectId: 'musicplay-a6b40',
    storageBucket: 'musicplay-a6b40.firebasestorage.app',
  );

}